export const CHAT = {
    UPDATE_COUNT_ONLINE_USERS: 'UPDATE_COUNT_ONLINE_USERS',
    NEW_MESSAGE: 'NEW_MESSAGE'
}

export const BALANCE = {
    NEW_BALANCE: 'NEW_BALANCE',
    NEW_DEMO_BALANCE: 'NEW_DEMO_BALANCE'
}

export const BONUSES = {
    CHANGE_SELECTED_DIAMONDS: 'CHANGE_SELECTED_DIAMONDS'
}

export const BET = {
    BET_HISTORY_ANSWER: 'BET_HISTORY_ANSWER',
    MY_BET_HISTORY_ANSWER: 'MY_BET_HISTORY_ANSWER'
}

export const DICE = {
    SEND_DICE_BET: 'SEND_DICE_BET',
    DICE_BET_RESULT: 'DICE_BET_RESULT'
}

export const ROULETTE = {
    TEAM_GAME_START: 'TEAM_GAME_START',
    TEAM_GAME_BET: 'TEAM_GAME_BET',
    SEND_TEAM_GAME_BET: 'SEND_TEAM_GAME_BET',
    TEAM_GAME_BET_ANSWER: 'TEAM_GAME_BET_ANSWER',
    TEAM_GAME_RESULT: 'TEAM_GAME_RESULT',
}

export const JACKPOT = {
    JACKPOT_GAME_START: 'JACKPOT_GAME_START',
    JACKPOT_GAME_BET: 'JACKPOT_GAME_BET',
    SEND_JACKPOT_GAME_BET: 'JACKPOT_GAME_BET',
    JACKPOT_GAME_BET_ANSWER: 'JACKPOT_GAME_BET_ANSWER',
    JACKPOT_GAME_RESULT: 'JACKPOT_GAME_RESULT',
}

export const BATTLE = {
    BATTLE_GAME_START: 'BATTLE_GAME_START',
    BATTLE_GAME_BET: 'BATTLE_GAME_BET',
    SEND_BATTLE_GAME_BET: 'SEND_BATTLE_GAME_BET',
    BATTLE_GAME_BET_ANSWER: 'BATTLE_GAME_BET_ANSWER',
    BATTLE_GAME_RESULT: 'BATTLE_GAME_RESULT',
}

export const CRASH = {
    CRASH_GAME_START: 'CRASH_GAME_START',
    CRASH_GAME_BET: 'CRASH_GAME_BET',
    SEND_CRASH_GAME_BET: 'SEND_CRASH_GAME_BET',
    CRASH_GAME_BET_ANSWER: 'CRASH_GAME_BET_ANSWER',
    CRASH_GAME_RESULT: 'CRASH_GAME_RESULT',
}
