export default {
  JACKPOT_GAME_START: 'JACKPOT_GAME_START',
  JACKPOT_GAME_BET: 'JACKPOT_GAME_BET',
  JACKPOT_GAME_BET_ANSWER: 'JACKPOT_GAME_BET_ANSWER',
  JACKPOT_GAME_RESULT: 'JACKPOT_GAME_RESULT',
}