export const MAIN_SITE_SETTINGS = {
  BASE_URL: 'BASE_URL',
};

export const SEO = {
  MAIN_PAGE_SEO: 'MAIN_PAGE_SEO',
  FAQ_SEO: 'FAQ_SEO',
  RULES_SEO: 'RULES_SEO',
  MINES_SEO: 'MINES_SEO',
  DICE_SEO: 'DICE_SEO',
  CRASH_SEO: 'CRASH_SEO',
  BATTLE_SEO: 'BATTLE_SEO',
  ROULETTE_SEO: 'ROULETTE_SEO',
  JACKPOT_SEO: 'JACKPOT_SEO',
  HILO_SEO: 'HILO_SEO',
};

export const MAIN_PAGE_FULL_BLOCK_CONTENT = 'MAIN_PAGE_FULL_BLOCK_CONTENT';

export const MAIN_PAGE_STATISTICS = {
  TOTAL_GAMES: 'MAIN_PAGE_STATISTICS_TOTAL_GAMES',
  LUCKY: 'MAIN_PAGE_STATISTICS_LUCKY_DAY'
}

export const AVAILABLE_GAMES = 'AVAILABLE_GAMES';

export const PAYMENT = {
  PAYMENT_BONUS_FIRST_PAY_COUNT_ACTIVATION: 'PAYMENT_BONUS_FIRST_PAY_COUNT_ACTIVATION',
  PAYMENT_BONUS_FIRST_PAY_AMOUNT: 'PAYMENT_BONUS_FIRST_PAY_AMOUNT',
  START_BALANCE: 'START_BALANCE',
  ACTIVE_PAYMENT_SYSTEM: 'ACTIVE_PAYMENT_SYSTEM',
  PAYMENT_INCOME_COMMISSION: 'PAYMENT_INCOME_COMMISSION',
  PAYMENT_OUTCOME_COMMISSION: 'PAYMENT_OUTCOME_COMMISSION',
  PAYMENT_OUTCOME_PHONES: 'PAYMENT_OUTCOME_PHONES',
  PAYMENT_OUTCOME_MIN_SUM: 'PAYMENT_OUTCOME_MIN_SUM',
  ACTIVE_BANK_CALLBACK_URL: 'ACTIVE_BANK_CALLBACK_URL'
};

export const ACTIVE_WEBSITE_URL = 'ACTIVE_WEBSITE_URL';

export const CHAT = {
  CHAT_LAST_COUNT_MESSAGES: 'CHAT_LAST_COUNT_MESSAGES',
  CHAT_MUTE_TIME: 'CHAT_MUTE_TIME',
  CHAT_IS_MUCH_WRITE_WITHOUT_PAYMENT:
    'CHAT_IS_MUCH_WRITE_WITHOUT_PAYMENT',
};

export const FAQ_PAGE_CONTENT = 'FAQ_PAGE_CONTENT';
export const RULES_PAGE_CONTENT = 'RULES_PAGE_CONTENT';

export const BONUSES = {
  PAYMENT: 'BONUS_PAYMENT',
  QUESTS: 'BONUS_EVERY_DAY_QUESTS',
  CHEST: 'BONUS_EVERY_DAY_CHEST_PRIZE',
  COUNT_DIAMOND_NEED_FOR_OPEN_CHEST: 'BONUS_EVERY_DAY_CHEST_COUNT_DIAMOND_NEED_FOR_OPEN',
  ONE_TIME: 'BONUS_ONE_TIME'
}

export const BASE_URL = 'BASE_URL';
export const ACTIVE_BANK_CALLBACK_URL = 'ACTIVE_BANK_CALLBACK_URL';
export const PAYMENT_OUTCOME_EMAILS = 'PAYMENT_OUTCOME_EMAILS'

export const SOCIAL = {
  FACEBOOK: 'SOCIAL_FACEBOOK',

  VK: 'SOCIAL_VKONTAKTE',

  TELEGRAM: 'SOCIAL_TELEGRAM',
  TELEGRAM_SUPPORT: 'SOCIAL_TELEGRAM_SUPPORT',
}

export const COMMISSION = {
  MINES_WIN_COMMISSION: 'MINES_WIN_COMMISSION',
  DICE_WIN_COMMISSION: 'DICE_WIN_COMMISSION',
  HILO_WIN_COMMISSION: 'HILO_WIN_COMMISSION',
  CRASH_WIN_COMMISSION: 'CRASH_WIN_COMMISSION',
}

export const DICE = {
  DICE_IMAGE: 'DICE_IMAGE',
  DICE_ICON: 'DICE_ICON',
  DICE_BET_COMMISSION: 'DICE_BET_COMMISSION',
  DICE_DEFAULT_WIN_CHANCE: 'DICE_DEFAULT_WIN_CHANCE',
  DICE_MIN_WIN_CHANCE: 'DICE_MIN_WIN_CHANCE',
  DICE_MAX_WIN_CHANCE: 'DICE_MAX_WIN_CHANCE',
  DICE_BET_MIN: 'DICE_BET_MIN',
  DICE_CHANCE_DEGRADATION: 'DICE_CHANCE_DEGRADATION',
  // DICE_BONUS_CHANCE: 'DICE_BONUS_CHANCE',
  // DICE_BONUS_2_CHANCE: 'DICE_BONUS_2_CHANCE',
}

export const CRASH = {
  CRASH_IMAGE: 'CRASH_IMAGE',
  CRASH_ICON: 'CRASH_ICON',
  CRASH_FAIL_S: 'CRASH_FAIL_S',
  CRASH_FAIL_M: 'CRASH_FAIL_M',
  CRASH_FAIL_B: 'CRASH_FAIL_B',
  CRASH_FAIL_H: 'CRASH_FAIL_H',
  CRASH_FAIL_U: 'CRASH_FAIL_U',
}

export const ROULETTE = {
  ROULETTE_IMAGE: 'ROULETTE_IMAGE',
  ROULETTE_ICON: 'ROULETTE_ICON',
  TEAM_GAME_GAIN_COMMISSION: 'TEAM_GAME_GAIN_COMMISSION',
}
